# --- CONFIGURAÇÃO PARA O AMBIENTE DE PRODUÇÃO (POSTGRESQL) ---

# URL de conexão com o seu banco de dados PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/produtosdunego

# Usuário e senha do seu banco de dados PostgreSQL
#spring.datasource.username=postgres
#spring.datasource.password=123

# Chave secreta do JWT para o ambiente de produção
#api.security.token.secret=49a8f3d6-e26e-4a88-9c6a-4b7d2f9b1e9c-produtos-du-nego

# Configurações do Hibernate para PostgreSQL
# Na PRIMEIRA VEZ que rodar, use "update" para que o Hibernate crie as tabelas.
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL gerado no console (bom para verificar o que está acontecendo)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# --- CONFIGURAÇÃO PARA O AMBIENTE (SQL SERVER) ---

# URL de conexão (Porta padrão 1433).
# 'encrypt=true;trustServerCertificate=true' são necessários nas versões mais novas do driver para evitar erros de certificado SSL em local.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=produtosdunego;encrypt=true;trustServerCertificate=true;

# Usuário e senha do seu SQL Server (Geralmente 'sa' ou o usuário que você criou)
spring.datasource.username=sa
spring.datasource.password=123

# Driver (Opcional, o Spring costuma detectar, mas garante que use o correto)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Chave secreta do JWT
api.security.token.secret=49a8f3d6-e26e-4a88-9c6a-4b7d2f9b1e9c-produtos-du-nego

# Configurações do Hibernate para SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Mostra o SQL gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Mantenha se você ainda estiver usando o data.sql para popular o banco)
spring.jpa.defer-datasource-initialization=true