# Configurações de conexão com o banco de dados H2
spring.datasource.url=jdbc:h2:mem:ProdutosDuNego
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Hibernate DDL e Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configurações do console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Log de SQL e erros detalhados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.security=DEBUG


# Chave secreta para assinatura e validação dos tokens JWT
# Pode ser uma chave simples para facilitar os testes.
api.security.token.secret=chave-simples-para-desenvolvimento-local