# Ativa o perfil de desenvolvimento por padrão (pode ser sobrescrito por variáveis de ambiente)
spring.profiles.active=producao

# Configurações do servidor
server.port=8080
server.servlet.context-path=/api

# Nome da aplicação
spring.application.name=ProdutosDuNego

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Permite que o Spring Boot execute o script data.sql na inicialização
 # spring.jpa.defer-datasource-initialization=true
# url swagger = http://localhost:8080/api/swagger-ui/index.html#/
# url h2 = http://localhost:8080/api/h2/